// Auto-generated by ts-rs. Do not edit manually.

export type AccessorKind = "get" | "set";

export type AccessorProperty = { span: Span, key: IrExpr, accessorKind: AccessorKind, params: Array<Param>, body: Block, };

export type Annotations = { scopeLevel: ScopeLevel | null, declarationKind: DeclKind | null, isAsync: boolean, isGenerator: boolean, isExport: boolean, isDefault: boolean, };

export type ArrayExpr = { span: Span, elements: Array<IrExpr | null>, };

export type ArrayPattern = { span: Span, elements: Array<Pattern | null>, };

export type Assignment = { span: Span, target: IrExpr, operator: string, value: IrExpr, };

export type AssignmentPattern = { span: Span, left: Pattern, right: IrExpr, };

export type AwaitExpr = { span: Span, argument: IrExpr, };

export type BinaryExpr = { span: Span, left: IrExpr, operator: string, right: IrExpr, };

export type Block = { span: Span, body: Array<IrNode>, };

export type BreakStmt = { span: Span, label: string | null, };

export type Call = { span: Span, callee: IrExpr, arguments: Array<IrExpr>, optional: boolean, };

export type CatchClause = { span: Span, param: string | null, body: Block, };

export type ClassDecl = { span: Span, name: string | null, superClass: IrExpr | null, body: Array<IrNode>, annotations: Annotations, };

export type ConditionalExpr = { span: Span, condition: IrExpr, consequent: IrExpr, alternate: IrExpr, };

export type ContinueStmt = { span: Span, label: string | null, };

export type CstNode = { kind: string, named: boolean, span: Span, text: string | null, children: Array<CstNode>, fieldName: string | null, };

export type DeclKind = "let" | "const" | "var" | "function" | "class" | "import";

export type ExportDecl = { span: Span, declaration: IrNode | null, specifiers: Array<ExportSpecifier>, source: string | null, isDefault: boolean, };

export type ExportSpecifier = { span: Span, local: string, exported: string, };

export type ExpressionStatement = { span: Span, expression: IrExpr, };

export type ForAnnotations = { kind: ForKind, };

export type ForKind = "standard" | "in" | "of";

export type ForStmt = { span: Span, init: IrNode | null, condition: IrExpr | null, update: IrExpr | null, body: Block, annotations: ForAnnotations, };

export type FunctionDecl = { span: Span, name: string | null, params: Array<Param>, body: Block, annotations: Annotations, isArrow: boolean, };

export type Identifier = { span: Span, name: string, };

export type IfStmt = { span: Span, condition: IrExpr, consequent: Block, alternate: IrNode | null, };

export type ImportDecl = { span: Span, specifiers: Array<ImportSpecifier>, source: string, };

export type ImportDefault = { span: Span, local: string, };

export type ImportNamed = { span: Span, imported: string, local: string, };

export type ImportNamespace = { span: Span, local: string, };

export type ImportSpecifier = { "kind": "default" } & ImportDefault | { "kind": "named" } & ImportNamed | { "kind": "namespace" } & ImportNamespace;

export type IrExpr = { "type": "assignment" } & Assignment | { "type": "call" } & Call | { "type": "memberAccess" } & MemberAccess | { "type": "binaryExpr" } & BinaryExpr | { "type": "identifier" } & Identifier | { "type": "literal" } & Literal | { "type": "unaryExpr" } & UnaryExpr | { "type": "updateExpr" } & UpdateExpr | { "type": "conditionalExpr" } & ConditionalExpr | { "type": "arrayExpr" } & ArrayExpr | { "type": "objectExpr" } & ObjectExpr | { "type": "functionExpr" } & FunctionDecl | { "type": "newExpr" } & NewExpr | { "type": "awaitExpr" } & AwaitExpr | { "type": "yieldExpr" } & YieldExpr | { "type": "templateLiteral" } & TemplateLiteral | { "type": "taggedTemplate" } & TaggedTemplate | { "type": "spreadExpr" } & SpreadExpr | { "type": "opaque" } & OpaqueExpr;

export type IrModule = { span: Span, body: Array<IrNode>, };

export type IrNode = { "type": "variableDecl" } & VariableDecl | { "type": "functionDecl" } & FunctionDecl | { "type": "classDecl" } & ClassDecl | { "type": "importDecl" } & ImportDecl | { "type": "exportDecl" } & ExportDecl | { "type": "if" } & IfStmt | { "type": "for" } & ForStmt | { "type": "while" } & WhileStmt | { "type": "switch" } & SwitchStmt | { "type": "tryCatch" } & TryCatchStmt | { "type": "return" } & ReturnStmt | { "type": "throw" } & ThrowStmt | { "type": "break" } & BreakStmt | { "type": "continue" } & ContinueStmt | { "type": "labeled" } & LabeledStmt | { "type": "expressionStatement" } & ExpressionStatement | { "type": "block" } & Block | { "type": "opaque" } & OpaqueNode;

export type KeyValueProperty = { span: Span, key: IrExpr, value: IrExpr, computed: boolean, };

export type LabeledStmt = { span: Span, label: string, body: IrNode, };

export type Literal = { span: Span, value: LiteralValue, };

export type LiteralValue = { "string": string } | { "number": number } | { "boolean": boolean } | "null" | "undefined";

export type MemberAccess = { span: Span, object: IrExpr, property: IrExpr, computed: boolean, optional: boolean, };

export type MethodProperty = { span: Span, key: IrExpr, params: Array<Param>, body: Block, computed: boolean, isAsync: boolean, isGenerator: boolean, };

export type NewExpr = { span: Span, callee: IrExpr, arguments: Array<IrExpr>, };

export type ObjectExpr = { span: Span, properties: Array<ObjectProperty>, };

export type ObjectPattern = { span: Span, properties: Array<ObjectPatternProperty>, };

export type ObjectPatternProperty = { "kind": "keyValue" } & PatternKeyValue | { "kind": "shorthand" } & PatternShorthand | { "kind": "rest" } & PatternRest;

export type ObjectProperty = { "kind": "keyValue" } & KeyValueProperty | { "kind": "shorthand" } & ShorthandProperty | { "kind": "method" } & MethodProperty | { "kind": "accessor" } & AccessorProperty | { "kind": "spread" } & SpreadProperty;

export type OpaqueExpr = { span: Span, cstKind: string, text: string, };

export type OpaqueNode = { span: Span, cstKind: string, text: string, };

export type Param = { span: Span, name: string, pattern: Pattern | null, defaultValue: IrExpr | null, };

export type Pattern = { "kind": "object" } & ObjectPattern | { "kind": "array" } & ArrayPattern | { "kind": "assignment" } & AssignmentPattern | { "kind": "rest" } & RestPattern;

export type PatternKeyValue = { span: Span, key: string, value: Pattern, };

export type PatternRest = { span: Span, name: string, };

export type PatternShorthand = { span: Span, name: string, defaultValue: IrExpr | null, };

export type Position = { 
/**
 * 0-based line number
 */
line: number, 
/**
 * 0-based column (byte offset within the line)
 */
column: number, 
/**
 * Byte offset from the start of the source
 */
offset: number, };

export type RestPattern = { span: Span, argument: Pattern, };

export type ReturnStmt = { span: Span, value: IrExpr | null, };

export type ScopeLevel = "block" | "function" | "module";

export type ShorthandProperty = { span: Span, name: string, };

export type Span = { start: Position, end: Position, };

export type SpreadExpr = { span: Span, argument: IrExpr, };

export type SpreadProperty = { span: Span, argument: IrExpr, };

export type SwitchCase = { span: Span, test: IrExpr | null, body: Array<IrNode>, };

export type SwitchStmt = { span: Span, discriminant: IrExpr, cases: Array<SwitchCase>, };

export type TaggedTemplate = { span: Span, tag: IrExpr, quasi: IrExpr, };

export type TemplateLiteral = { span: Span, quasis: Array<string>, expressions: Array<IrExpr>, };

export type ThrowStmt = { span: Span, argument: IrExpr, };

export type TryCatchStmt = { span: Span, tryBlock: Block, catchClause: CatchClause | null, finallyBlock: Block | null, };

export type UnaryExpr = { span: Span, operator: string, operand: IrExpr, prefix: boolean, };

export type UpdateExpr = { span: Span, operator: string, operand: IrExpr, prefix: boolean, };

export type VariableDecl = { span: Span, name: string, value: IrExpr | null, pattern: Pattern | null, annotations: Annotations, };

export type WhileStmt = { span: Span, condition: IrExpr, body: Block, isDoWhile: boolean, };

export type YieldExpr = { span: Span, argument: IrExpr | null, delegate: boolean, };
