// Auto-generated by ts-rs. Do not edit manually.

export type Annotations = { scopeLevel: ScopeLevel | null, declarationKind: DeclKind | null, isAsync: boolean, isGenerator: boolean, isExport: boolean, isDefault: boolean, };

export type Assignment = { span: Span, target: IrExpr, operator: string, value: IrExpr, };

export type BinaryExpr = { span: Span, left: IrExpr, operator: string, right: IrExpr, };

export type Block = { span: Span, body: Array<IrNode>, };

export type BreakStmt = { span: Span, label: string | null, };

export type Call = { span: Span, callee: IrExpr, arguments: Array<IrExpr>, };

export type CatchClause = { span: Span, param: string | null, body: Block, };

export type ClassDecl = { span: Span, name: string | null, superClass: IrExpr | null, body: Array<IrNode>, annotations: Annotations, };

export type ContinueStmt = { span: Span, label: string | null, };

export type CstNode = { kind: string, named: boolean, span: Span, text: string | null, children: Array<CstNode>, fieldName: string | null, };

export type DeclKind = "let" | "const" | "var" | "function" | "class" | "import";

export type ExpressionStatement = { span: Span, expression: IrExpr, };

export type ForAnnotations = { kind: ForKind, };

export type ForKind = "standard" | "in" | "of";

export type ForStmt = { span: Span, init: IrNode | null, condition: IrExpr | null, update: IrExpr | null, body: Block, annotations: ForAnnotations, };

export type FunctionDecl = { span: Span, name: string | null, params: Array<Param>, body: Block, annotations: Annotations, };

export type Identifier = { span: Span, name: string, };

export type IfStmt = { span: Span, condition: IrExpr, consequent: Block, alternate: IrNode | null, };

export type IrExpr = { "type": "assignment" } & Assignment | { "type": "call" } & Call | { "type": "memberAccess" } & MemberAccess | { "type": "binaryExpr" } & BinaryExpr | { "type": "identifier" } & Identifier | { "type": "literal" } & Literal | { "type": "opaque" } & OpaqueExpr;

export type IrModule = { span: Span, body: Array<IrNode>, };

export type IrNode = { "type": "variableDecl" } & VariableDecl | { "type": "functionDecl" } & FunctionDecl | { "type": "classDecl" } & ClassDecl | { "type": "if" } & IfStmt | { "type": "for" } & ForStmt | { "type": "while" } & WhileStmt | { "type": "switch" } & SwitchStmt | { "type": "tryCatch" } & TryCatchStmt | { "type": "return" } & ReturnStmt | { "type": "break" } & BreakStmt | { "type": "continue" } & ContinueStmt | { "type": "expressionStatement" } & ExpressionStatement | { "type": "block" } & Block | { "type": "opaque" } & OpaqueNode;

export type Literal = { span: Span, value: LiteralValue, };

export type LiteralValue = { "string": string } | { "number": number } | { "boolean": boolean } | "null" | "undefined";

export type MemberAccess = { span: Span, object: IrExpr, property: IrExpr, computed: boolean, };

export type OpaqueExpr = { span: Span, cstKind: string, text: string, };

export type OpaqueNode = { span: Span, cstKind: string, text: string, };

export type Param = { span: Span, name: string, };

export type Position = { 
/**
 * 0-based line number
 */
line: number, 
/**
 * 0-based column (byte offset within the line)
 */
column: number, 
/**
 * Byte offset from the start of the source
 */
offset: number, };

export type ReturnStmt = { span: Span, value: IrExpr | null, };

export type ScopeLevel = "block" | "function" | "module";

export type Span = { start: Position, end: Position, };

export type SwitchCase = { span: Span, test: IrExpr | null, body: Array<IrNode>, };

export type SwitchStmt = { span: Span, discriminant: IrExpr, cases: Array<SwitchCase>, };

export type TryCatchStmt = { span: Span, tryBlock: Block, catchClause: CatchClause | null, finallyBlock: Block | null, };

export type VariableDecl = { span: Span, name: string, value: IrExpr | null, annotations: Annotations, };

export type WhileStmt = { span: Span, condition: IrExpr, body: Block, isDoWhile: boolean, };
