[package]
name = "ehrmantraut"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ehrmantraut-core = { path = "../core" }
ehrmantraut-js-lowering = { path = "../js-lowering" }
napi = { version = "3.0.0", features = ["serde-json", "async"] }
napi-derive = "3.0.0"
rayon = "1"
serde_json = "1"

[build-dependencies]
napi-build = "2"
